window.OW_PEOPLE_HISTORY = [
  {name:'Pastor Olabisi',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from April-June 2026 attendance registers.'},
  {name:'Bro Patrick',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from April-June 2026 attendance registers.'},
  {name:'Bro Eric',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Bro Isaac',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Daddy Obulor',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Also appears as Bro Obulor/Daddy Obulor.'},
  {name:'Mummy Obulor',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Bro Samuel',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Bro Kayode',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-06-01',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Bro Opeyemi',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Handwritten as Opeyemi/Opeyemi on registers.'},
  {name:'Pastor Agbanimu',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Mrs Agbanimu',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-14',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Sis Agbanimu',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Bro Daniel',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Adult/campus entry; separate from youth Daniel.'},
  {name:'Bro Kevin',type:'Visitor',group:'Men',phone:'',email:'',lastSeen:'2026-05-31',status:'Follow-up',notes:'Marked as newcomer on May 31 register.'},
  {name:'Sis Lola',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Sis Purity',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Sis Better',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-08',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Mummy Ifekwe',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Also appears as Sis Ifekwe on some registers.'},
  {name:'Sis Dorcas',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Appears in adult/campus sections.'},
  {name:'Mummy Eunice',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Also appears as Sis Eunice.'},
  {name:'Sis Blessing',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Grandma Bovi',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-15',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Sis Dhun',type:'Visitor',group:'Women',phone:'',email:'',lastSeen:'2026-04-26',status:'Follow-up',notes:'Appears in April register and visitation notes.'},
  {name:'Sis Anne',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-04-26',status:'Connected',notes:'Campus member entry.'},
  {name:'Sis Jemima',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Extracted from attendance registers.'},
  {name:'Sis Phebe',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Spelling read from handwritten register.'},
  {name:'Sis Dom',type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Handwritten register entry.'},
  {name:"Sis Eric's Mum",type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Family-label entry from register.'},
  {name:'Sis Adejoke',type:'Visitor',group:'Women',phone:'',email:'',lastSeen:'2026-05-31',status:'Follow-up',notes:'Marked as newcomer on May 31 register.'},
  {name:"Adejoke's Mum",type:'Visitor',group:'Women',phone:'',email:'',lastSeen:'2026-05-31',status:'Follow-up',notes:'Family-label newcomer entry from May 31 register.'},
  {name:"Adejoke's Dad",type:'Visitor',group:'Men',phone:'',email:'',lastSeen:'2026-05-31',status:'Follow-up',notes:'Family-label newcomer entry from May 31 register.'},
  {name:'Bro Colin',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-04-26',status:'Connected',notes:'Campus member entry.'},
  {name:'Bro Emmanuel',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-04-26',status:'Connected',notes:'Campus member entry.'},
  {name:"Bro God's Chosen",type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-06-01',status:'Connected',notes:'Also written as Bro Godschosen/God’s Chosen.'},
  {name:'Chinemerem',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-04-26',status:'Connected',notes:'Spelling read from April register.'},
  {name:'Bro Peculiar',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Spelling sometimes appears as Perculiar.'},
  {name:'Bro Eben',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Campus/member entry.'},
  {name:'Bro Iniolu',type:'Member',group:'Campus',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Spelling read from handwritten register.'},
  {name:'Bro Prince',type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-05-17',status:'Connected',notes:'Extracted from attendance register.'},
  {name:"God's Chosen's Mum",type:'Member',group:'Women',phone:'',email:'',lastSeen:'2026-06-01',status:'Connected',notes:'Family-label entry from register.'},
  {name:"God's Chosen's Dad",type:'Member',group:'Men',phone:'',email:'',lastSeen:'2026-05-31',status:'Connected',notes:'Family-label entry from register.'},
  {name:'Victoria',type:'Member',group:'Youth',phone:'',email:'',lastSeen:'2026-06-15',status:'Connected',notes:'Youth entry from attendance registers.'},
  {name:'David',type:'Member',group:'Youth',phone:'',email:'',lastSeen:'2026-06-15',status:'Connected',notes:'Youth entry from attendance registers.'},
  {name:'Daniel',type:'Member',group:'Youth',phone:'',email:'',lastSeen:'2026-06-15',status:'Connected',notes:'Youth entry from attendance registers.'},
  {name:'Wonderful',type:'Visitor',group:'Youth',phone:'',email:'',lastSeen:'2026-06-01',status:'Follow-up',notes:'Marked as newcomer on May 31 register; appears again June 1.'},
  {name:'Olushola',type:'Visitor',group:'Youth',phone:'',email:'',lastSeen:'2026-05-31',status:'Follow-up',notes:'Marked as newcomer on May 31 register.'},
  {name:'Nathan',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Child entry from attendance registers.'},
  {name:'Michelle',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Child entry from attendance registers.'},
  {name:'Iretomiwa',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-06-18',status:'Connected',notes:'Child entry from attendance registers.'},
  {name:'Eric Junior',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-04-26',status:'Connected',notes:'Child entry from April register.'},
  {name:'Jaylen',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Child entry from attendance registers.'},
  {name:'Kezia',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Child entry from attendance registers.'},
  {name:'Joshua',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Child entry from attendance register.'},
  {name:'Jordan',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Child entry from attendance register.'},
  {name:'Jennifer',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-24',status:'Connected',notes:'Child entry from attendance register.'},
  {name:"God's Light",type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-06-01',status:'Connected',notes:'Child entry from attendance registers.'},
  {name:"God's Chosen Child 1",type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-14',status:'Connected',notes:'Family-label child entry from register.'},
  {name:"God's Chosen Child 2",type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-14',status:'Connected',notes:'Family-label child entry from register.'},
  {name:'Agbanimu Grandchild 1',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-14',status:'Connected',notes:'Family-label child entry from register.'},
  {name:'Agbanimu Grandchild 2',type:'Member',group:'Children',phone:'',email:'',lastSeen:'2026-05-14',status:'Connected',notes:'Family-label child entry from register.'}
];
